[platformio]
default_envs = esp32-4848s040

[env:esp32-4848s040]
platform = platformio/espressif32@6.9.0
board = esp32-4848s040
framework = arduino
lib_ldf_mode = deep+
lib_compat_mode = off
monitor_speed = 115200
upload_speed = 921600
upload_port = COM9
monitor_port = COM9

board_build.partitions = app3M_fat9M_16MB.csv

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DCORE_DEBUG_LEVEL=0

lib_deps =
  bblanchon/ArduinoJson@6.17.2
  adafruit/Adafruit GFX Library@1.12.6

[env:esp32-4848s040-test]
extends = env:esp32-4848s040
build_flags =
  ${env:esp32-4848s040.build_flags}
  -DEVETEC_TEST_BUILD=1
